### ISSUE TITLE
Naive question, shade not found

### ISSUE THREAD

**Issue by WenyinWei** [rubenwiersma/blender-pointcloud#1]
Hi @rubenwiersma , I found your blend file pretty beautiful and suitable for introducing basic operations offered by animate note. Would you mind letting me know how you inject the light to the cow so there is a shade on the plane in 'example_render.png'? I add a plane and a light but I can't see the shade. I am a newcomer to Blender so please forgive me if this question is too naive.

I am trying to animate n-body interaction physical simulation by Blender. The script really helps a lot!

**Comment by rubenwiersma** [comment]
Hi @WenyinWei, thanks for your message and I'm happy the script has been of use to you! You're well on your way. Some troubleshooting tips:
1. What view mode are you in? To see shadows, make sure you are in 'Rendered mode' (the right-most option).
<img width="622" alt="Screenshot 2022-04-19 at 15 50 48" src="https://user-images.githubusercontent.com/9115743/164019095-07546eee-b452-4192-8430-9a7461206e14.png">
2. The lights in the standard scene are area lights. These tend to give very diffuse shadows. You can remove the area lights and add a point light, which should give you more noticeable shadows.

You might find Silvia Sellán's guide on rendering paper figures helpful as well: https://www.silviasellan.com/blender_figure.html

**Comment by WenyinWei** [comment]
Hi @rubenwiersma , thank you very much for the prompt reply! So fast. I followed your suggestion to change the view mode, things seem to keep the same. And `Render-> render image` always gives me the same result without shade no matter how I change the lights.  Maybe there is something wrong with my render setting? Let me explore more tomorrow.

**Comment by WenyinWei** [comment]
It is pretty strange that I can have shade in a normal blender project file but not in pointcloud_animationnodes.blend .

![image](https://user-images.githubusercontent.com/33152225/164131509-f3557cfe-90ff-4cc1-839c-dfe8e5b82361.png)

I added an Icosphere in the two scenes to make the lighting effect evident. It seems that in pointcloud_animationnodes.blend the lighting of scene does not depend on the existing light objects, which really puzzles me. Maybe I made some foolish mistakes on lighting that I have not yet noticed?

![image](https://user-images.githubusercontent.com/33152225/164131393-dbaecae5-48c2-4c22-99df-d740ed8741ef.png)

**Comment by rubenwiersma** [comment]
If you look closely at the right side of the icosphere, there is a very dim and soft shadow, just barely noticeable. I think that's because the point light has a very large radius (giving softer shadows). Try dialing the radius of that light down to something like 0.25 and move the light around a bit to see if that gives you the shadows you want.

<img width="411" alt="Screenshot 2022-04-20 at 12 03 09" src="https://user-images.githubusercontent.com/9115743/164204009-343835de-fde7-43c5-9174-258e85753877.png">

If that doesn't work, could you respond with the Blender version you are using? That will help me with trying to replicate the issue.

**Comment by WenyinWei** [comment]
Thank you @rubenwiersma ! Although the radius of light is not the true answer, it inspired me. The background of the world has its own colour and works like a light with an infinity radius emitting rays from everywhere. I turned the colour of the background to pure black and the shadows come! Thank you! Nice of you to help me a lot.

![image](https://user-images.githubusercontent.com/33152225/164223805-47cc4909-f580-4051-9dac-bd13a4857844.png)

![image](https://user-images.githubusercontent.com/33152225/164224466-db6db202-9736-4929-8acd-46b6de564633.png)

**Comment by rubenwiersma** [comment]
Ah, I see! I think the difference with the setup on my computer is that my background is transparent (Render properties > Film > Transparent). Glad you figured it out!
<img width="347" alt="Screenshot 2022-04-20 at 14 17 06" src="https://user-images.githubusercontent.com/9115743/164228521-43c08d94-c021-4e09-a1e8-40c426479799.png">

By the way, if you would like a transparent background and still have shadows rendered, you can select the plane object and then make it a shadow catcher (Object properties > Visibility > Shadow catcher).
<img width="338" alt="Screenshot 2022-04-20 at 14 18 22" src="https://user-images.githubusercontent.com/9115743/164228701-ea992c73-bc1c-4e05-b9c7-9f92a21d3858.png">
